use crate::db::models::ThreadJournalEntry;
use std::path::Path;

/// Render a living spec markdown document from journal entries and conventions.
pub fn render_living_spec(
    journal_entries: &[ThreadJournalEntry],
    conventions: &[String],
) -> String {
    let mut doc = String::new();

    doc.push_str("# agmux Living Spec\n\n");
    doc.push_str("> Auto-generated by agmux. Do not edit manually.\n\n");

    // Project Conventions
    if !conventions.is_empty() {
        doc.push_str("## Project Conventions\n\n");
        for conv in conventions {
            doc.push_str(&format!("- {}\n", conv));
        }
        doc.push('\n');
    }

    // Decisions
    let decisions: Vec<&ThreadJournalEntry> = journal_entries
        .iter()
        .filter(|e| e.kind == "Decision" && e.is_archived == 0)
        .collect();
    if !decisions.is_empty() {
        doc.push_str("## Decisions\n\n");
        for entry in &decisions {
            doc.push_str(&format!("### {}\n\n{}\n\n", entry.title, entry.content));
        }
    }

    // Completed Work (capped at 20)
    let completed: Vec<&ThreadJournalEntry> = journal_entries
        .iter()
        .filter(|e| e.kind == "CompletedWork" && e.is_archived == 0)
        .rev()
        .take(20)
        .collect();
    if !completed.is_empty() {
        doc.push_str("## Completed Work\n\n");
        for entry in &completed {
            doc.push_str(&format!("- **{}**: {}\n", entry.title, entry.content));
        }
        doc.push('\n');
    }

    // Known Issues
    let issues: Vec<&ThreadJournalEntry> = journal_entries
        .iter()
        .filter(|e| e.kind == "KnownIssue" && e.is_archived == 0)
        .collect();
    if !issues.is_empty() {
        doc.push_str("## Known Issues\n\n");
        for entry in &issues {
            doc.push_str(&format!("- **{}**: {}\n", entry.title, entry.content));
        }
        doc.push('\n');
    }

    // Pinned Context
    let pinned: Vec<&ThreadJournalEntry> = journal_entries
        .iter()
        .filter(|e| e.kind == "Pin" && e.is_archived == 0)
        .collect();
    if !pinned.is_empty() {
        doc.push_str("## Pinned Context\n\n");
        for entry in &pinned {
            doc.push_str(&format!("- **{}**: {}\n", entry.title, entry.content));
        }
        doc.push('\n');
    }

    doc
}

/// Write the living spec to the work directory as AGMUX.md,
/// and create CLAUDE.md and AGENTS.md as symlinks to it.
/// Also adds the generated files to .git/info/exclude if possible.
pub fn write_living_spec(work_dir: &str, content: &str) -> anyhow::Result<()> {
    let base = Path::new(work_dir);
    let agmux_path = base.join("AGMUX.md");

    // Write the main AGMUX.md file
    // Remove legacy XANOM.md if present so we don't leave a stale product name on disk
    let legacy = base.join("XANOM.md");
    if legacy.exists() {
        let _ = std::fs::remove_file(&legacy);
    }
    std::fs::write(&agmux_path, content)?;

    // Create symlinks for CLAUDE.md and AGENTS.md
    let symlinks = ["CLAUDE.md", "AGENTS.md"];
    for link_name in &symlinks {
        let link_path = base.join(link_name);

        // Remove existing file/symlink if present
        if link_path.exists() || link_path.symlink_metadata().is_ok() {
            let _ = std::fs::remove_file(&link_path);
        }

        #[cfg(unix)]
        {
            use std::os::unix::fs::symlink;
            symlink("AGMUX.md", &link_path)?;
        }
    }

    // Add to .git/info/exclude if possible
    add_to_git_exclude(work_dir)?;

    Ok(())
}

fn add_to_git_exclude(work_dir: &str) -> anyhow::Result<()> {
    let exclude_path = Path::new(work_dir)
        .join(".git")
        .join("info")
        .join("exclude");

    // Only proceed if .git/info exists
    if let Some(parent) = exclude_path.parent() {
        if !parent.exists() {
            return Ok(());
        }
    } else {
        return Ok(());
    }

    let entries_to_add = ["AGMUX.md", "XANOM.md", "CLAUDE.md", "AGENTS.md"];

    let existing_content = if exclude_path.exists() {
        std::fs::read_to_string(&exclude_path).unwrap_or_default()
    } else {
        String::new()
    };

    let mut lines_to_append = Vec::new();
    for entry in &entries_to_add {
        if !existing_content.lines().any(|line| line.trim() == *entry) {
            lines_to_append.push(*entry);
        }
    }

    if !lines_to_append.is_empty() {
        use std::io::Write;
        let mut file = std::fs::OpenOptions::new()
            .create(true)
            .append(true)
            .open(&exclude_path)?;

        // Add a newline before our entries if the file doesn't end with one
        if !existing_content.is_empty() && !existing_content.ends_with('\n') {
            writeln!(file)?;
        }

        for line in &lines_to_append {
            writeln!(file, "{}", line)?;
        }
    }

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::db::models::ThreadJournalEntry;

    fn entry(kind: &str, title: &str, content: &str, archived: i32) -> ThreadJournalEntry {
        ThreadJournalEntry {
            id: format!("id-{}-{}", kind, title),
            thread_id: "t1".to_string(),
            kind: kind.to_string(),
            title: title.to_string(),
            content: content.to_string(),
            source: "User".to_string(),
            confidence: None,
            created_by: None,
            created_at: "2026-01-01T00:00:00Z".to_string(),
            updated_at: "2026-01-01T00:00:00Z".to_string(),
            is_archived: archived,
        }
    }

    #[test]
    fn render_includes_header() {
        let doc = render_living_spec(&[], &[]);
        assert!(doc.starts_with("# agmux Living Spec\n\n"));
        assert!(doc.contains("> Auto-generated by agmux. Do not edit manually."));
    }

    #[test]
    fn render_empty_inputs_emits_only_header() {
        let doc = render_living_spec(&[], &[]);
        assert!(!doc.contains("## Project Conventions"));
        assert!(!doc.contains("## Decisions"));
        assert!(!doc.contains("## Completed Work"));
        assert!(!doc.contains("## Known Issues"));
        assert!(!doc.contains("## Pinned Context"));
    }

    #[test]
    fn render_includes_conventions_when_present() {
        let conventions = vec!["Use tabs".to_string(), "Prefer enums".to_string()];
        let doc = render_living_spec(&[], &conventions);
        assert!(doc.contains("## Project Conventions"));
        assert!(doc.contains("- Use tabs\n"));
        assert!(doc.contains("- Prefer enums\n"));
    }

    #[test]
    fn render_omits_conventions_when_empty() {
        let doc = render_living_spec(&[], &[]);
        assert!(!doc.contains("## Project Conventions"));
    }

    #[test]
    fn render_decisions_section() {
        let entries = vec![entry("Decision", "Use SQLite", "It is embedded.", 0)];
        let doc = render_living_spec(&entries, &[]);
        assert!(doc.contains("## Decisions"));
        assert!(doc.contains("### Use SQLite"));
        assert!(doc.contains("It is embedded."));
    }

    #[test]
    fn render_filters_archived_entries() {
        let entries = vec![
            entry("Decision", "Active", "live", 0),
            entry("Decision", "Archived", "old", 1),
        ];
        let doc = render_living_spec(&entries, &[]);
        assert!(doc.contains("### Active"));
        assert!(!doc.contains("### Archived"));
    }

    #[test]
    fn render_filters_by_kind() {
        let entries = vec![
            entry("Decision", "D1", "d", 0),
            entry("Note", "N1", "n", 0),
            entry("KnownIssue", "I1", "i", 0),
        ];
        let doc = render_living_spec(&entries, &[]);
        // Note kind is not rendered
        assert!(!doc.contains("N1"));
        assert!(doc.contains("### D1"));
        assert!(doc.contains("- **I1**: i"));
    }

    #[test]
    fn render_completed_work_capped_at_20() {
        let entries: Vec<ThreadJournalEntry> = (0..30)
            .map(|i| entry("CompletedWork", &format!("W{}", i), "done", 0))
            .collect();
        let doc = render_living_spec(&entries, &[]);
        assert!(doc.contains("## Completed Work"));
        // Count list items in completed section
        let completed_section = doc
            .split("## Completed Work")
            .nth(1)
            .expect("completed section exists");
        let count = completed_section.matches("- **W").count();
        assert_eq!(count, 20, "completed work should cap at 20");
    }

    #[test]
    fn render_completed_work_uses_reverse_order() {
        // .rev().take(20) means the LAST inserted entries come first.
        let entries = vec![
            entry("CompletedWork", "First", "1", 0),
            entry("CompletedWork", "Second", "2", 0),
            entry("CompletedWork", "Third", "3", 0),
        ];
        let doc = render_living_spec(&entries, &[]);
        let completed = doc
            .split("## Completed Work")
            .nth(1)
            .expect("completed section");
        let first_idx = completed.find("First").unwrap();
        let third_idx = completed.find("Third").unwrap();
        assert!(third_idx < first_idx, "newest (Third) should appear before First");
    }

    #[test]
    fn render_known_issues_and_pinned_context() {
        let entries = vec![
            entry("KnownIssue", "Bug A", "broken", 0),
            entry("Pin", "Note X", "important", 0),
        ];
        let doc = render_living_spec(&entries, &[]);
        assert!(doc.contains("## Known Issues"));
        assert!(doc.contains("- **Bug A**: broken"));
        assert!(doc.contains("## Pinned Context"));
        assert!(doc.contains("- **Note X**: important"));
    }

    #[test]
    fn render_full_document_section_order() {
        let conventions = vec!["Convention1".to_string()];
        let entries = vec![
            entry("Decision", "D1", "d", 0),
            entry("CompletedWork", "C1", "c", 0),
            entry("KnownIssue", "I1", "i", 0),
            entry("Pin", "P1", "p", 0),
        ];
        let doc = render_living_spec(&entries, &conventions);

        let conv_idx = doc.find("## Project Conventions").unwrap();
        let dec_idx = doc.find("## Decisions").unwrap();
        let comp_idx = doc.find("## Completed Work").unwrap();
        let issue_idx = doc.find("## Known Issues").unwrap();
        let pin_idx = doc.find("## Pinned Context").unwrap();

        assert!(conv_idx < dec_idx);
        assert!(dec_idx < comp_idx);
        assert!(comp_idx < issue_idx);
        assert!(issue_idx < pin_idx);
    }

    // ── write_living_spec ────────────────────────────────────────────────────

    #[test]
    fn write_living_spec_creates_agmux_and_symlinks() {
        let dir = tempfile::tempdir().unwrap();
        let work_dir = dir.path().to_string_lossy().to_string();
        write_living_spec(&work_dir, "# spec body\n").unwrap();

        let agmux = dir.path().join("AGMUX.md");
        assert!(agmux.is_file());
        let body = std::fs::read_to_string(&agmux).unwrap();
        assert!(body.contains("# spec body"));

        // CLAUDE.md and AGENTS.md should be symlinks pointing at AGMUX.md
        for name in ["CLAUDE.md", "AGENTS.md"] {
            let link = dir.path().join(name);
            assert!(link.exists(), "{name} should exist after write_living_spec");
            #[cfg(unix)]
            {
                let target = std::fs::read_link(&link).unwrap();
                assert_eq!(target.to_string_lossy(), "AGMUX.md");
            }
        }
    }

    #[test]
    fn write_living_spec_replaces_existing_symlinks() {
        let dir = tempfile::tempdir().unwrap();
        let work_dir = dir.path().to_string_lossy().to_string();
        // Pre-create CLAUDE.md as a regular file. write_living_spec should
        // remove and replace it with a symlink.
        std::fs::write(dir.path().join("CLAUDE.md"), "old content").unwrap();
        write_living_spec(&work_dir, "v2\n").unwrap();

        let claude = dir.path().join("CLAUDE.md");
        #[cfg(unix)]
        {
            let target = std::fs::read_link(&claude).unwrap();
            assert_eq!(target.to_string_lossy(), "AGMUX.md");
        }
    }

    #[test]
    fn write_living_spec_overwrites_agmux_md_content() {
        let dir = tempfile::tempdir().unwrap();
        let work_dir = dir.path().to_string_lossy().to_string();
        write_living_spec(&work_dir, "first\n").unwrap();
        write_living_spec(&work_dir, "second\n").unwrap();
        let body = std::fs::read_to_string(dir.path().join("AGMUX.md")).unwrap();
        assert!(body.contains("second"));
        assert!(!body.contains("first"));
    }

    // ── add_to_git_exclude (via write_living_spec wrapper) ───────────────────

    #[test]
    fn add_to_git_exclude_skips_when_no_dot_git_info() {
        // .git/info doesn't exist; write_living_spec must still succeed
        // (silently no-ops the exclude step).
        let dir = tempfile::tempdir().unwrap();
        let work_dir = dir.path().to_string_lossy().to_string();
        write_living_spec(&work_dir, "spec\n").unwrap();
        // No .git/info created or expected
        assert!(!dir.path().join(".git").join("info").exists());
    }

    #[test]
    fn add_to_git_exclude_creates_or_appends_when_info_exists() {
        let dir = tempfile::tempdir().unwrap();
        let info_dir = dir.path().join(".git").join("info");
        std::fs::create_dir_all(&info_dir).unwrap();
        let work_dir = dir.path().to_string_lossy().to_string();

        write_living_spec(&work_dir, "spec\n").unwrap();

        let exclude_body = std::fs::read_to_string(info_dir.join("exclude")).unwrap();
        assert!(exclude_body.contains("AGMUX.md"));
        assert!(exclude_body.contains("CLAUDE.md"));
        assert!(exclude_body.contains("AGENTS.md"));
    }

    #[test]
    fn add_to_git_exclude_appends_only_missing_entries() {
        let dir = tempfile::tempdir().unwrap();
        let info_dir = dir.path().join(".git").join("info");
        std::fs::create_dir_all(&info_dir).unwrap();
        let exclude_path = info_dir.join("exclude");
        // Pre-seed with one of the entries; the rest should be appended.
        std::fs::write(&exclude_path, "# existing\nAGMUX.md\n").unwrap();
        let work_dir = dir.path().to_string_lossy().to_string();

        write_living_spec(&work_dir, "spec\n").unwrap();

        let body = std::fs::read_to_string(&exclude_path).unwrap();
        // AGMUX.md should appear exactly once (from pre-seed)
        let count = body.matches("AGMUX.md").count();
        assert_eq!(count, 1);
        assert!(body.contains("CLAUDE.md"));
        assert!(body.contains("AGENTS.md"));
    }

    #[test]
    fn add_to_git_exclude_adds_newline_when_file_does_not_end_with_one() {
        let dir = tempfile::tempdir().unwrap();
        let info_dir = dir.path().join(".git").join("info");
        std::fs::create_dir_all(&info_dir).unwrap();
        let exclude_path = info_dir.join("exclude");
        // Pre-seed without trailing newline.
        std::fs::write(&exclude_path, "# existing").unwrap();
        let work_dir = dir.path().to_string_lossy().to_string();

        write_living_spec(&work_dir, "spec\n").unwrap();

        let body = std::fs::read_to_string(&exclude_path).unwrap();
        assert!(body.contains("# existing\n"));
        assert!(body.contains("AGMUX.md"));
    }
}
